apiVersion: apps/v1
kind: Deployment
metadata:
  name: vvytfg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vvytfg
  template:
    metadata:
      labels:
        app: vvytfg
    spec:
      containers:
      - image: okteto.dev/vvytfg:latest
        name: vvytfg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "27c3bfb9-e82a-4603-8bee-727d5c26d5f3"
        - name: Vless_Path
          value: "/vl5po7"
        - name: Vmess_UUID
          value: "27c3bfb9-e82a-4603-8bee-727d5c26d5f3"
        - name: Vmess_Path
          value: "/vm6r5tf"
        - name: Share_Path
          value: "/v2link"
